### PR TITLE
Update both heroku to take randomly names

### PR DESCRIPTION
**Pull request by onlyhavecans**

### CODE REVIEW

**Comment by weppos** [comment]
I added @sbastn as reviewer as he's been taking care of several services.

@sbastn do you think we should let the customer enter the whole Heroku host (e.g. antonym-rivalry-b163r7kvcv32we2uaw69gd8a.herokudns.com) or just the random part (e.g. antonym-rivalry-b163r7kvcv32we2uaw69gd8a)?

**Comment by weppos** [comment]
@onlyhavecans do you have confirmation this change affects both SSL and non-SSL?

**Comment by onlyhavecans** [comment]
> do you have confirmed this change affects both SSL and non-SSL?

No, and their support site does not help. Do we have a contact or test we can set up?

**Comment by weppos** [comment]
> Do we have a contact or test we can set up?

You can probably setup a test app in our Heroku account, add a domain without SSL and see what they suggest to use as target hostname.

**Comment by onlyhavecans** [comment]
Building a test app with no SSL I verified the interface is now unified. If @dnsimple/developers can verify my test is accurate we can likely simplify this down to a single 1-click

screen shot 2019-02-26 at 09 39 22

**Comment by weppos** [comment]
> we can likely simplify this down to a single 1-click

Yes. I agree. Sadly, we can't currently remove a one-click service. But I believe @sbastn added an option to deprecate an old one.

@sbastn can you please help?

**Comment by sbastn** [comment]
@weppos and @onlyhavecans, I have simplified the setup, so instead of telling the user to manipulate the text to remove "herokudns.com" from it, they can just paste it all in since they have it in their clipboard.

@weppos is correct, we cannot delete a one-click service, but you can deprecate it following this section on the README: https://github.com/dnsimple/dnsimple-services/#remove-services

**Comment by weppos** [comment]
@sbastn can you please deprecate `heroku-ssl`?

**Comment by onlyhavecans** [comment]
I deprecated the service per the docs and re-requested review. What is my deployment steps after approval? Can someone work with me to verify the deploy?

**Comment by weppos** [comment]
@onlyhavecans the service repo is updated on deploy. So after a merge it's sufficient to deploy the app and the service changes will be loaded in the app.

You will be able to confirm the changes are live by trying to apply the service and the new settings should appear.

**Pull request merged**
