### PR TITLE
Add Blackbell one-click

### PR DESCRIPTION
**Pull request by ulmen**
This adds a one-click service for Blackbell.

Blackbell is the simplest way to sell services. Read more at www.blackbell.com.

### CODE REVIEW

**Comment by sbastn** [comment]
Thanks for submitting a PR for your service. We found an error that you should fix. Unfortunately, we don't support interpolating the domain name in the `field` section for the `config.json`. You currently have `"append": ".{{domain}}",` but it renders exactly that string in the UI:

screen shot 2018-05-04 at 4 13 02 pm

You have 2 options:

1. Remove `"append": ".{{domain}}",`. This would create the following prompt:

screen shot 2018-05-04 at 4 21 18 pm

2. Change the `append` field to `"append": ".blackbell.com",` and update the copy to clarify that this is the matching subdomain in your blackbell configuration.

Let us know if you have any question.

**Comment by sbastn** [comment]
@ulmen Thank you for submitting this PR. I left some feedback for you to take action on. Let us know if you have any question.

**Comment by ulmen** [comment]
@sbastn We chose 1st option, PR was updated. Thanks for review!

**Comment by sbastn** [comment]
@ulmen thank you for making the changes. I am merging this PR. Blackbell will appear as a service as soon as we deploy, which will be today.

**Pull request merged**
