### PR TITLE
Add Platform.sh service

### PR DESCRIPTION
**Pull request by xtfer**
This PR adds DNS configuration for Platform.sh, a PaaS for web applications.

### CODE REVIEW

**Comment by sbastn** [comment]
@xtfer thank you very much for submitting this PR!

Since the service is added in the context of a domain, there is no need to ask for the domain name again. Here is what I see on our UI when I test your one click:

Screen Shot 2019-09-24 at 2 40 01 PM

You can skip asking for a domain, simplifying the configuration. I'll add some notes to your configuration.
Screen Shot 2019-09-24 at 2 51 50 PM

**Comment by xtfer** [comment]
@sbastn Thanks. I had originally intended to call-back to our service to add that domain, but removed it. You are obviously correct that it is now redundant. I'll modify and resubmit. :)

**Comment by xtfer** [comment]
@sbastn Updated, please review. Thanks.

**Comment by sbastn** [comment]
@xtfer, thank you for making these updates. One thing I noticed is that you removed the ALIAS record on the root/naked domain. Is this intentional? Let me know, I'll be happy to merge this.

**Comment by xtfer** [comment]
@sbastn No, it wasnt intentional. /facepalm.

I'll open a new one to add the ALIAS back in.

**Pull request merged**
