### PR TITLE
Add gigalixir service.

### PR DESCRIPTION
**Pull request by jesseshieh**

### CODE REVIEW

**Comment by OleMchls** [comment]
Thanks @jesseshieh could you please provide a link to the documentation on how to set up custom domains with Gigalixir?

**Comment by schwindtkevin** [comment]
@OleMchls I'm not affiliated in any way with gigalixir, but I think this is what you're looking for: https://gigalixir.readthedocs.io/en/latest/main.html?highlight=domain#custom-domains

**Comment by OleMchls** [comment]
> @OleMchls I'm not affiliated in any way with gigalixir, but I think this is what you're looking for: https://gigalixir.readthedocs.io/en/latest/main.html?highlight=domain#custom-domains

Thanks @schwindtkevin, I am just wondering what's the designated CNAME target when setting up a custom domain. I can't find it in the docs (you links).

I would infer from the documentation that it's `https://$APP_NAME.gigalixirapp.com/`? But I have never personally used it before.

**Comment by jesseshieh** [comment]
When you run `gigalixir domains:add $domain`, you get a CNAME to use that will always look like `$domain.gigalixirdns.com`

For example, if you run `gigalixir domains:add www.example.com`, your CNAME will be `www.example.com.gigalixirdns.com`

**Comment by OleMchls** [comment]
Thanks for the additional information @jesseshieh 👍 

To use `{{ subdomain }}` you would need to define this as a field. You can refer to the [AWS Lightsail](https://github.com/dnsimple/dnsimple-services/blob/master/services/amazon-lightsail/config.json#L8-L15) for examples.

Currently, it'd look like this:

Screenshot 2020-05-20 at 15 50 37

**Comment by jesseshieh** [comment]
Thanks for the help, Ole. I'll add the subdomain as a field, but I'm wondering, does the user have to type in their subdomain in this case? If that's the case, it might be less confusing if they just type in the entire fully qualified domain instead similar to how Heroku does it. What do you think?

**Comment by OleMchls** [comment]
> Thanks for the help, Ole. I'll add the subdomain as a field, but I'm wondering, does the user have to type in their subdomain in this case? If that's the case, it might be less confusing if they just type in the entire fully qualified domain instead similar to how Heroku does it. What do you think?

Given the similarity between Gigalizir to Heroku I think it makes sense to do it in a similar way. :) Thanks @jesseshieh

**Comment by jesseshieh** [comment]
Thanks again, Ole. I just updated the config. Can you take another look? 

If they want to point both their apex domain and a subdomain such as www to gigalixir, then they'll have to run `gigalixir domains:add` twice, once for the apex and once for the www one e.g.
```
gigalixir domains:add example.com
gigalixir domains:add www.example.com
```

Then they'll have to create a DNS record for each one. If it's the apex, I guess they'll have to use ALIAS. If it's not the apex, we normally use CNAME, but I think ALIAS should also work so for simplicity, I just changed the config to ask for the fully qualified domain name and made it always use ALIAS. So they'll have to use this one-click service for every subdomain they want to point to gigalixir. Do you think that would be fine?

The Heroku config.json seems to just assume they will have both the apex and the www domain and no others which is certainly the most common case, but then I wonder what happens when they want to add another subdomain like `foo.example.com`.

**Comment by OleMchls** [comment]
@jesseshieh thanks for providing this update. The current solution has one little problem; It'd only work for the APEX domain, not because you choose ALIAS but because the record name is always empty.

Let's say you want to use the APEX plus admin.liveview.tech you will need the following records:

ALIAS liveview.tech liveview.tech.gigalixir.com
CNAME _(or ALIAS)_ admin.liveview.tech admin.liveview.tech.gigalixir.com

That second record needs `admin` as the record name. Before we go too fancy with this one-click service I'd like to explain why these exist. The idea is to help kickstart integrations. More complex setup will require good old records via our record editor. As Gigalixir is very similar to Heroku I'd recommend that we stick close to the Heroku implementation, that one is also one of our most popular ones and we have very little issues with it so far :)

**Comment by jesseshieh** [comment]
No problem, thanks Ole. I pushed a change to make it basically the same as Heroku. Can you take another look?

**Comment by OleMchls** [comment]
You can now use the Gigalixir service on dnsimple.com, thanks for your contributions :)

**Pull request merged**
