### PR TITLE
Updates format configuration

### LINKED ISSUE #90: Format configuration is deprecated
See https://help.format.com/en/articles/2645459-connecting-a-custom-domain, the user needs to enter a value for `mysite` when creating the CNAME with the value `mysite.format.com`. Their documentation also point to the use of a URL to redirect the naked domain to the "www" subdomain.

### PR DESCRIPTION
**Pull request by sbastn**
Closes #90. This PR updates the one-click service for Format.com. I also refreshed their logo.

Based on their documentation https://help.format.com/en/articles/2645459-connecting-a-custom-domain, the one-click service has been updated to:

1. Prompt for a site name. They call this "Format address".
2. Redirect the apex/root to "www"

# 👀 How to test this

1. Checkout this branch.
2. From the DNSimple app, point the services rake file to your local repo.
```
# File: lib/tasks/services.rake
5     sh("git clone /Users/me/projects/dnsimple/dnsimple-services tmp/dnsimple-services")
```
3. From the DNSimple app, execute `rake services:import`
4. From the DNSimple app, add the Format one-click service to any domain. You should be prompted to enter the Format site, and see that it creates a CNAME on the "www" subdomain and a URL record on the apex/root.
5. On `/services`, you should see Format listed

### CODE REVIEW

**Comment by aeden** [comment]
@sbastn do you have a Format site hosted with DNSimple that we can test this with?

**Comment by sbastn** [comment]
@aeden We have a few Format sites that still work with the current configuration (just a CNAME record with the value "format.com"), but without knowing their Format Address (if they have one specified), we cannot complete the configuration.
Screen Shot 2020-05-14 at 6 21 18 PM

Any domain that has the one-click service installed will continue to work as is, or at least until Format decides to shut down that configuration. These changes would apply to new configurations only.

**Comment by aeden** [comment]
A small example of why I think this matters: they have the URL record set to http... why not https? Are they supporting HTTPS for the custom domains?

**Comment by sbastn** [comment]
They take care of doing the redirect to HTTPS: https://help.format.com/en/articles/2645467-secure-ssl-domain-connections

I'd like stick to their recommendations. It makes it easier to upgrade in the future if anything changes.

**Pull request merged**
